[package]
name = "gnalc"
version = "0.1.0"

[dependencies]
clap = "2.33.3"         # cli-app框架
pest = "2.1.3"          # lexer工具
pest_derive = "2.1.0"   # lexer派生宏
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm11-0"] }
