on: [push]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build and run tests
      run: cargo test
    - name: Test no default
      run: cargo test --no-default-features
