on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm

    - name: Build
      run: cargo build

    - name: Test Compilation
      run: cargo test tests::test_compile -- --exact --nocapture

    # - name: Test Correctness
      
